version: '2'
services:
  web:
    build: .

    volumes:
      - .:/Src

    working_dir: /Src

    command: sh -c "pip3 intall -r requirements.txt && gunicorn project.wsgi --log-file -"

    ports:
     - "8055:8055"
